# Generated by Django 6.0.6 on 2026-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hero_text",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
