# Generated by Django 6.0.6 on 2026-06-22 14:33
import os
from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.conf import settings

def create_superuser(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin_deploy')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin123')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
    
    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            password=make_password(password),
            is_superuser=True,
            is_staff=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_profile_hero_text"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
